version: '3.4'

services:
  hopeai:
    image: hopeai
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8001:8001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
